# Generated by Django 3.2.4 on 2021-06-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLoginInfoAndCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Prefer Not To Say')]),
        ),
    ]
