# Generated by Django 3.2.4 on 2021-06-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLoginInfoAndCRUD', '0002_auto_20210618_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Prefer Not To Say')]),
        ),
    ]
