# Generated by Django 3.2.4 on 2021-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLoginInfoAndCRUD', '0005_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
